### ISSUE TITLE
这个商城是怎么防止超卖的？有兄弟还记得吗？

### ISSUE THREAD

**Issue by wardseptember** [NiceSeason/gulimall-learning#20]
这个商城是怎么防止超卖的？有兄弟还记得吗？

**Comment by 8bun** [comment]
> 这个商城是怎么防止超卖的？有兄弟还记得吗？

信号量啊，秒杀接口有个信号量抢占，但是可能会少卖

**Comment by wardseptember** [comment]
> > 这个商城是怎么防止超卖的？有兄弟还记得吗？
> 
> 信号量啊，秒杀接口有个信号量抢占，但是可能会少卖

信号量是限流的作用，还有通过乐观锁的方式，更新库存。我又仔细看了下
